#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : mvn-servicemix-pom
Version  : 5
Release  : 3
URL      : https://github.com/apache/servicemix-pom/archive/servicemix-pom-5.tar.gz
Source0  : https://github.com/apache/servicemix-pom/archive/servicemix-pom-5.tar.gz
Source1  : https://repo1.maven.org/maven2/org/apache/servicemix/servicemix-pom/5/servicemix-pom-5.pom
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: mvn-servicemix-pom-data = %{version}-%{release}

%description
No detailed description available

%package data
Summary: data components for the mvn-servicemix-pom package.
Group: Data

%description data
data components for the mvn-servicemix-pom package.


%prep

%build

%install
mkdir -p %{buildroot}/usr/share/java/.m2/repository/org/apache/servicemix/servicemix-pom/5
cp %{SOURCE1} %{buildroot}/usr/share/java/.m2/repository/org/apache/servicemix/servicemix-pom/5/servicemix-pom-5.pom


%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/java/.m2/repository/org/apache/servicemix/servicemix-pom/5/servicemix-pom-5.pom
